### ISSUE TITLE
Why does my script run so slow?

### ISSUE THREAD

**Issue by monikappv** [datopian/zen-of-data#3]
What could be the reason that my script is being loaded/runs so slowly from the command prompt? (I am talking about 10-15mins here). 
Could it be because of too many requests sent to a website (in this case around 1500), or have I just designed the script poorly?

**Comment by gavram** [comment]
Most likely, the problem is too many requests.
With every request your code makes, there is a response time of the server where that page resides.
For a better conclusion, I need to see your code.
If there's an API to get the content you need, it's the best solution to speed up the code

**Comment by rufuspollock** [comment]
FIXED. Probably the number of requests (if each request took 0.5s and this is sequential then this is 750s = 12m+)
