### ISSUE TITLE
Empty tbody tag

### ISSUE THREAD

**Issue by monikappv** [datopian/zen-of-data#4]
What could be the reason that printing a html table returns an empty tbody tag? The request is working [=200], I can print the website's content, I also target the right table, but the tbody tag is empty when I print the table. That's the piece of code:
 
```
der_table = soup.find_all('table')[0]
print(der_table)
```

**Comment by RobGrootjen** [comment]
@monikappv  Was this resolved? If not the webpage might have like "Anti scraper protection" so you will need to use selenium and web driver. If you can share your whole code I can take a look at it.

**Comment by rufuspollock** [comment]
INVALID.

@monikappv you need a lot more detail / context. e.g. the source site, code context  etc etc. As such this can't be answered.
