### ISSUE TITLE
What is the best way to include units of measure in datasets?

### ISSUE THREAD

**Issue by glgoose** [datopian/zen-of-data#9]
**Question**: What is the best way to include units of measure e.g. currencies (USD, EUR), meters (m), … in tabular data sets?
**Hypothesis**:
* Add to header i.e. at the end of the name in brackets e.g. Price (US$)
* Add to values e.g. 150 US$
* Add separate header e.g. ‘Unit of Measure’, ‘Currency’, ...

**Comment by rufuspollock** [comment]
FIXED. Use the Frictionless Data units spec (wip) https://github.com/frictionlessdata/specs/issues/537
